### ISSUE TITLE
Install error: FileNotFoundError

### ISSUE THREAD

**Issue by DaSh-More** [bentettmar/python-translator#2]
Error output:

```
Collecting python-translator
  Using cached python-translator-1.0.2.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\danila\AppData\Local\Temp\pip-install-_i6bq6os\python-translator_ae02d4d2b6f745f683febfb0eae37a76\setup.py", line 3, in <module>
          with open('readme.md') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bennyscripts** [comment]
The reason for this is due to the setup.py trying to read a file that doesnt exist to pypi. I will upload a new version with the readme as a string. I will comment again once that is live.

**Comment by bennyscripts** [comment]
Sorry for the inconvenience, if you download the current latest release ([v1.0.3](https://pypi.org/project/python-translator/1.0.3/)) everything should work :)
